version: '3.7'

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - docker-mysql
    command: ["./wait-for-it.sh docker-mysql:3306"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/contacts_app?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: acousin
      SPRING_DATASOURCE_PASSWORD: OpenWT74!
    networks:
      - backend
  docker-mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: contacts_app
      MYSQL_USER: acousin
      MYSQL_PASSWORD: OpenWT74!
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

networks:
  backend: